spring:
  redis:
    host: 192.168.79.133
    database: 0
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
